name: Tests

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Setup PNPM
        uses: pnpm/action-setup@v5
        with:
          version: 10

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Run tests
        run: pnpm exec playwright test

  test-container:
    runs-on: ubuntu-latest
    container: node:24
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v5
        with:
          version: 10

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Run tests
        run: pnpm exec playwright test
        env:
          FK_ENV_CONTAINER: '1'
